export {default as Home} from "../pages/Home"
export {default as Register} from "../pages/Register"
export {default as Login} from "../pages/Login"
export {default as Forget_pass} from "../pages/Forgetpass"
export {default as Error_404} from "../pages/404-pages"
